apiVersion: v1
kind: ConfigMap
metadata:
  name: vllm-config
  namespace: vllm
data:
  MODEL_ID: "MODEL_NAME"
  MODEL_PATH: "MODEL_PATH"
  VLLM_HOST: "0.0.0.0"
  VLLM_PORT: "8000"
  DTYPE: "bfloat16"
  MAX_MODEL_LEN: "8192"
  GPU_MEMORY_UTILIZATION: "0.90"
